### ISSUE TITLE
License not included

### ISSUE THREAD

**Issue by ernestoallely** [Lenius/laravel-basket#2]
Although the file compose.json specifies that the code is distributed under the MIT license the license is not included on the code and therefore this could create confusion, if the code is distributed under that license this should be included.

Note that if the code has no license is not considered open source, https://www.gnu.org/licenses/license-list.en.html#NoLicense. While not having a license is not an issue per se, it would be good if this could be clarified.

**Comment by cjonstrup** [comment]
Fixed
